config/routes.rb
Rails.application.routes.draw do
  namespace :operators_backoffice do
    get 'welcome/index'
  end
  namespace :pilots_backoffice do
    get 'welcome/index'
    get 'profile', to: 'profile#edit'
    patch 'profile', to: 'profile#update'
    resources :my_next_maneuvers, only: [:index, :edit, :update]
    resources :my_performed_maneuvers, only: [:index, :edit]
    resources :dashboard, only: [:index]
  end

  namespace :operators_backoffice do
    get 'welcome/index'
    get 'profile', to: 'profile#edit'
    patch 'profile', to: 'profile#update'
    resources :pilot, only: [:index, :edit, :update, :new, :create, :destroy]
    resources :operator, only: [:index, :edit, :update, :new, :create, :destroy]
    resources :vessel, only: [:index, :edit, :update, :new, :create, :destroy]
    resources :terminal, only: [:index, :edit, :update, :new, :create, :destroy]
    resources :next_maneuvers, only: [:index, :edit, :update, :new, :create, :destroy]
    resources :performed_maneuvers, only: [:index, :edit]
  end
  
  devise_for :operators
  devise_for :pilots
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :site do
    get  'welcome/index'
    get  'maneuvers_performed/index'
    get  'next_maneuvers/index'
    #get  'search', to: 'search#questions'
    #get  'subject/:subject_id/:subject', to: 'search#subject' , as: 'search_subject'
    #post 'answer', to: 'answer#question'
  end
   #toda vez que a aplicação for iniciada com seu endereço padrão, será redirecionada para welcome#index
   root to: 'site/welcome#index'
end

app/controllers/operators_backoffice/next_maneuvers_controller.rb
class OperatorsBackoffice::NextManeuversController < OperatorsBackofficeController
    def index 
        @maneuvers = Maneuver.order('date_maneuver ASC, time_maneuver ASC')
    end

    def edit
        @maneuver = Maneuver.find(params[:id])
        
        @hour_options = []
        (0..23).each  do |hour|
            @hour_options.push([hour,hour])
        end

        @min_options = []
        (0..59).each  do |min|
            @min_options.push([min,min])
        end

        @pilot_profile_options = []
        all_pilot_profile = PilotProfile.all
        all_pilot_profile.each do |pilot_profile|
            @pilot_profile_options.push(["#{pilot_profile.first_name} #{pilot_profile.last_name}", pilot_profile.id])
        end

        #Maneuver type
        @maneuver_type_options = [["Entrada",1],["Saída",2]]
        if @maneuver.type_maneuver == "Entrada"
            @maneuver_type_id = 1
        else
            @maneuver_type_id = 2
        end

        @vessel_options = []
        all_vessels = Vessel.all
        all_vessels.each do |vessel|
            @vessel_options.push([vessel.name, vessel.id])
        end

        @terminal_options = []
        all_terminals = Terminal.all
        all_terminals.each do |terminal|
            @terminal_options.push([terminal.name, terminal.id])
        end

    end

    def update
        @maneuver = Maneuver.find(params[:id])
        @maneuver.date_maneuver = params[:maneuver][:date_maneuver]
        @maneuver.time_maneuver =  Time.new(2018,1,1,params[:maneuver][:hour],params[:maneuver][:minute],0)
        @maneuver.pilot_profile = PilotProfile.find(params[:maneuver][:pilot_profile][:pilot_profile_id])
        if params[:maneuver][:maneuver_type] == "1"
            @maneuver.type_maneuver = "Entrada"
        else
            @maneuver.type_maneuver = "Saída"
        end

        @maneuver.vessel = Vessel.find(params[:maneuver][:vessel][:vessel_id])
        @maneuver.vessel_displacement = params[:maneuver][:vessel_displacement].to_f
        @maneuver.terminal = Terminal.find(params[:maneuver][:terminal][:terminal_id])

        if  @maneuver.save
            #bypass_sign_in(@pilot)
            redirect_to edit_operators_backoffice_next_maneuver_path, notice: "Manobra atualizada com sucesso!"
        else
            render :edit
        end

    end

    def destroy
        @maneuver = Maneuver.find(params[:id])
        if  @maneuver.destroy
            redirect_to operators_backoffice_next_maneuvers_path, notice: "Manobra apagada com sucesso!"
        else
            render :edit
        end
    end

    def new
        @maneuver = Maneuver.new

        @hour_options = []
        (0..23).each  do |hour|
            @hour_options.push([hour,hour])
        end

        @min_options = []
        (0..59).each  do |min|
            @min_options.push([min,min])
        end

        @pilot_profile_options = []
        all_pilot_profile = PilotProfile.all
        all_pilot_profile.each do |pilot_profile|
            @pilot_profile_options.push(["#{pilot_profile.first_name} #{pilot_profile.last_name}", pilot_profile.id])
        end

        #Maneuver type
        @maneuver_type_options = [["Entrada",1],["Saída",2]]
        if @maneuver.type_maneuver == "Entrada"
            @maneuver_type_id = 1
        else
            @maneuver_type_id = 2
        end

        @vessel_options = []
        all_vessels = Vessel.all
        all_vessels.each do |vessel|
            @vessel_options.push([vessel.name, vessel.id])
        end

        @terminal_options = []
        all_terminals = Terminal.all
        all_terminals.each do |terminal|
            @terminal_options.push([terminal.name, terminal.id])
        end

    end

    def create
        @maneuver = Maneuver.new

        @maneuver.date_maneuver = params[:maneuver][:date_maneuver]
        @maneuver.time_maneuver =  Time.new(2018,1,1,params[:maneuver][:hour],params[:maneuver][:minute],0)
        @maneuver.pilot_profile = PilotProfile.find(params[:maneuver][:pilot_profile][:pilot_profile_id])
        if params[:maneuver][:maneuver_type] == "1"
            @maneuver.type_maneuver = "Entrada"
        else
            @maneuver.type_maneuver = "Saída"
        end

        @maneuver.vessel = Vessel.find(params[:maneuver][:vessel][:vessel_id])
        @maneuver.vessel_displacement = params[:maneuver][:vessel_displacement].to_f
        @maneuver.terminal = Terminal.find(params[:maneuver][:terminal][:terminal_id])
        @maneuver.relatory = Relatory.create!
        @maneuver.operator_profile = OperatorProfile.find(current_operator.operator_profile.id)

        if @maneuver.save!
            #bypass_sign_in(@pilot)
            redirect_to operators_backoffice_next_maneuvers_path, notice: "Manobra criada com sucesso!"
        else
           render :new
        end

    end
end

app/controllers/operators_backoffice/operator_controller.rb
class OperatorsBackoffice::OperatorController < OperatorsBackofficeController
    def index
        @operators = Operator.all
    end

    def edit
        @operator = Operator.find(params[:id])
        @operator.build_operator_profile if @operator.operator_profile.blank?
    end

    def update
        @operator = Operator.find(params[:id])
        if @operator.update(params_operator)
            redirect_to edit_operators_backoffice_operator_path, notice: "Perfil do Operador atualizado com sucesso!"
        else
            render :edit
        end
    end

    def destroy
        @operator = Operator.find(params[:id])
        if @operator.destroy
            redirect_to operators_backoffice_operator_index_path, notice: "Perfil do Operador apagado com sucesso!"
        else
            render :edit
        end
    end

    def new
        @operator = Operator.new({ "email"=> "default@default.com"})
    end

    def create
        @operator = Operator.new(params_operator_simplified)
        if @operator.save
            #bypass_sign_in(@pilot)
            redirect_to operators_backoffice_operator_index_path, notice: "Perfil do Operador criado com sucesso!"
        else
           render :new
        end
    end

    private
    def params_operator
        params.require(:operator).permit(:email, :password, :password_confirmation,
        operator_profile_attributes: [:id, :first_name, :last_name, :address, :birthdate])
    end

    def params_operator_simplified
        params.require(:operator).permit(:email, :password, :password_confirmation)
    end


end

app/controllers/operators_backoffice/performed_maneuvers_controller.rb
class OperatorsBackoffice::PerformedManeuversController < OperatorsBackofficeController
    def index
        @maneuvers = Maneuver.where( { is_finished: true }).order('date_maneuver ASC, time_maneuver ASC')
    end

    
    def edit
        @maneuver = Maneuver.find(params[:id])
    end
    
end

app/controllers/operators_backoffice/pilot_controller.rb
class OperatorsBackoffice::PilotController < OperatorsBackofficeController
    def index
        @pilots = Pilot.all
    end

    def edit
        @pilot = Pilot.find(params[:id])
        @pilot.build_pilot_profile if @pilot.pilot_profile.blank?
    end

    def update
        @pilot = Pilot.find(params[:id])
        if @pilot.update(params_pilot)
            #bypass_sign_in(@pilot)
            redirect_to edit_operators_backoffice_pilot_path, notice: "Perfil do Prático atualizado com sucesso!"
        else
           render :edit
        end
    end

    def new
       @pilot = Pilot.new({ "email"=> "default@default.com"})
    end

    def destroy
        @pilot = Pilot.find(params[:id])
        if @pilot.destroy
          redirect_to operators_backoffice_pilot_index_path, notice: "Prático apagado com sucesso"
        else
           render :index
        end
      end

    def create
        @pilot = Pilot.new(params_pilot_simplified)
        if @pilot.save
            #bypass_sign_in(@pilot)
            redirect_to operators_backoffice_pilot_index_path, notice: "Perfil do Prático criado com sucesso!"
        else
           render :new
        end
    end
    

    private
    def params_pilot
        params.require(:pilot).permit(:email, :password, :password_confirmation,
        pilot_profile_attributes: [:id, :first_name, :last_name, :address, :birthdate])
    end

    def params_pilot_simplified
        params.require(:pilot).permit(:email, :password, :password_confirmation)
    end

end

app/controllers/operators_backoffice/profile_controller.rb
class OperatorsBackoffice::ProfileController < OperatorsBackofficeController
    before_action :set_user
    
    def edit
        @operator.build_operator_profile if @operator.operator_profile.blank?
    end

    def update
        if @operator.update(params_operator)
            bypass_sign_in(@operator)
            redirect_to operators_backoffice_profile_path, notice: "Perfil do Operador atualizado com sucesso!"
        else
           render :edit
        end
    end

    private

    def set_user
        @operator = Operator.find(current_operator.id)
    end

    def params_operator
        params.require(:operator).permit(:email, :password, :password_confirmation,
        operator_profile_attributes: [:id, :first_name, :last_name, :address, :birthdate])
    end

end

app/controllers/operators_backoffice/terminal_controller.rb
class OperatorsBackoffice::TerminalController < OperatorsBackofficeController
    def index
        @terminals = Terminal.all
    end

    def edit
        @terminal = Terminal.find(params[:id])
    end

    def update
        @terminal = Terminal.find(params[:id])

        if @terminal.update(params_terminal)
            redirect_to edit_operators_backoffice_terminal_path, notice: "Terminal atualizado com sucesso!"
        else
            render :edit
        end

    end

    def destroy
        @terminal = Terminal.find(params[:id])
        if @terminal.destroy
            redirect_to operators_backoffice_terminal_index_path, notice: "Terminal apagado com sucesso!"
        else
            render :edit
        end
    end

    def new
        @terminal = Terminal.new
    end

    def create
        @terminal = Terminal.new(params_terminal)
        if @terminal.save
            #bypass_sign_in(@pilot)
            redirect_to operators_backoffice_terminal_index_path, notice: "Terminal criado com sucesso!"
        else
           render :new
        end
        
    end

    private

    def params_terminal
        params.require(:terminal).permit(:name, :cargo, :url_image)
    end

end

app/controllers/operators_backoffice/vessel_controller.rb
class OperatorsBackoffice::VesselController < OperatorsBackofficeController
    def index
        @vessels = Vessel.all
    end

    def edit
        @vessel = Vessel.find(params[:id])
    end

    def update
        @vessel = Vessel.find(params[:id])
        if @vessel.update(params_vessel)
            redirect_to edit_operators_backoffice_vessel_path, notice: "Navio atualizado com sucesso!"
        else
            render :edit
        end
    end

    def destroy
        @vessel = Vessel.find(params[:id])
        if @vessel.destroy
            redirect_to operators_backoffice_vessel_index_path, notice: "Navio apagado com sucesso!"
        else
            render :edit
        end
    end

    def new
        @vessel = Vessel.new
    end

    def create
        @vessel = Vessel.new(params_vessel)
        if @vessel.save
            #bypass_sign_in(@pilot)
            redirect_to operators_backoffice_vessel_index_path, notice: "Navio criado com sucesso!"
        else
           render :new
        end
    end
    private

    def params_vessel
        params.require(:vessel).permit(:name, :mmsi, :length, :width, :type_vessel, :url_image)
    end

end

app/controllers/operators_backoffice/welcome_controller.rb
class OperatorsBackoffice::WelcomeController < OperatorsBackofficeController
  def index
  end
end

app/controllers/operators_backoffice_controller.rb
class OperatorsBackofficeController < ApplicationController
    layout 'operators_backoffice'
end

app/helpers/operators_backoffice/next_maneuvers_helper.rb
module OperatorsBackoffice::NextManeuversHelper
end

app/helpers/operators_backoffice/operator_helper.rb
module OperatorsBackoffice::OperatorHelper
end

app/helpers/operators_backoffice/performed_maneuvers_helper.rb
module OperatorsBackoffice::PerformedManeuversHelper
end

app/helpers/operators_backoffice/pilot_helper.rb
module OperatorsBackoffice::PilotHelper
end

app/helpers/operators_backoffice/profile_helper.rb
module OperatorsBackoffice::ProfileHelper
end

app/helpers/operators_backoffice/terminal_helper.rb
module OperatorsBackoffice::TerminalHelper
end

app/helpers/operators_backoffice/vessel_helper.rb
module OperatorsBackoffice::VesselHelper
end

app/helpers/operators_backoffice/welcome_helper.rb
module OperatorsBackoffice::WelcomeHelper
end

app/helpers/operators_backoffice_helper.rb
module OperatorsBackofficeHelper
end

app/views/operators_backoffice/performed_maneuvers/edit.html.erb
<div class="row">
    <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
            <div class="x_title">
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <% if @maneuver.errors.any?%>
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <h5 class="alert-heading">Erros Encontrados</h5>
                        <ul>
                            <% @maneuver.errors.full_messages.each  do |message| %>
                            <li style="color:black; font-size:15px"> <%= message %></li>
                            <%end%>
                        </ul>
                        <button class="close" type="button" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                <% end %>

                <%= form_with(url:'#', model: @maneuver, local: true) do |form| %>
                    <%= form.fields_for :relatory do |relatory_form| %>
                       <div class="item form-group">
                        <div class="row" >
                            <%=relatory_form.label 'Descrição da Manobra', class:"col-md-4 mb-1", style:"color:black; font-size:20px"%>
                        </div>
                        
                        <div class="row">
                          <div class="col-md-8 mb-3 ">
                            <%=relatory_form.text_area :maneuver_description, value: @maneuver.relatory.maneuver_description, class:"form-control", rows: 10, :required => 'required', readonly: true%>
                          </div>
                        </div>

                    <div class="item form-group">
                        <div class="row">
                            <%=relatory_form.label 'Tendências do Navio', class:"col-md-4 mb-1",style:"color:black; font-size:20px"%>
                        </div>
                        <div class="row">
                          <div class="col-md-8 mb-3">
                            <%=relatory_form.text_area :vessel_tendecies, value:  @maneuver.relatory.vessel_tendecies, class:"form-control", rows: 10, :required => 'required', readonly: true %>
                          </div>
                        </div>
                            
                        <div class="item form-group">
                            <div class="row">
                                    <div class="col-md-8 mb-3">
                                        <%=relatory_form.label 'Nota para segurança da manobra', class:"col-md-6 mb-1", style:"color:black; font-size:20px"%>
                                        <%=relatory_form.text_field :maneuver_safety, value:  @maneuver.relatory.maneuver_safety, class:"form-control", :required => 'required', readonly: true %>
                                </div>
                            </div>
                        </div>

                         <div class="item form-group">
                            <div class="row">
                                    <div class="col-md-8 mb-3">
                                        <%=relatory_form.label 'Nota para segurança da escada', class:"col-md-6 mb-1", style:"color:black; font-size:20px"%>
                                        <%=relatory_form.text_field :ladder_safety, value:  @maneuver.relatory.ladder_safety, class:"form-control", :required => 'required', readonly: true %>
                                </div>
                            </div>
                        </div>
                    <%end%>

        
                    </div>
                    

                <% end %>
                

                    <div class="ln_solid"></div>
                        <div class="item form-group">
                            <div class="col-lg-10 col-lg-10 offset-lg-3">
                            <%= link_to "Voltar", operators_backoffice_performed_maneuvers_path, class:"btn btn-primary"%>
                        </div>
                    </div>

              

            </div>
        </div>
    </div>
</div>

app/views/operators_backoffice/performed_maneuvers/index.html.erb
<h1> Manobras Executadas</h1>
<div class="w3-padding w3-white notranslate">
<div class="table-responsive">
<table class="table table-hover">
    <thead>
        <tr>
        <th>Data</th>
        <th>Horário</th>
        <th>Prático</th>
        <th>Tipo de Manobra</th>
        <th>Navio</th>
        <th>Comprimento</th>
        <th>Boca</th>
        <th>Deslocamento</th>
        <th>Foto</th>
        <th>Terminal</th>
        <th>Tipo de Carga</th>
        <th>Foto</th>
        <th>Operador</th>
         <th>Link Relatório</th>
        </tr>
    </thead>
    <tbody>
    <% @maneuvers.each do |maneuver| %>
        
        <tr>
            <td><%= "#{maneuver.date_maneuver.day}/#{maneuver.date_maneuver.month}/#{maneuver.date_maneuver.year}" %></td>
            <td><%= maneuver.time_maneuver.strftime("%k:%M") %></td>
            <td><%= "#{maneuver.pilot_profile.first_name} #{maneuver.pilot_profile.last_name}" %></td>
            <td><%= maneuver.type_maneuver%></td>
             <td><%= maneuver.vessel.name%></td>
             <td><%= maneuver.vessel.length%></td>
             <td><%= maneuver.vessel.width%></td>
             <td><%= maneuver.vessel_displacement%></td>
            <td><%= image_tag maneuver.vessel.url_image, width:100, height:50 %></td>
             <td><%= maneuver.terminal.name%></td>
             <td><%= maneuver.terminal.cargo%></td>
            <td><%= image_tag maneuver.terminal.url_image, width:100, height:50 %></td>
            <td><%= "#{maneuver.operator_profile.first_name} #{maneuver.operator_profile.last_name}" %></td>         
            <td style="width: 120px">
                <%= link_to "Relatório", edit_operators_backoffice_performed_maneuver_path(maneuver.id)%>
            </td>
            
        </tr>
    <% end %>
    </tbody>
</table>
</div>
</div>