config/routes.rb
Rails.application.routes.draw do
  namespace :operators_backoffice do
    get 'welcome/index'
  end
  namespace :pilots_backoffice do
    get 'welcome/index'
    get 'profile', to: 'profile#edit'
    patch 'profile', to: 'profile#update'
    resources :my_next_maneuvers, only: [:index, :edit, :update]
    resources :my_performed_maneuvers, only: [:index, :edit]
    resources :dashboard, only: [:index]
  end

  namespace :operators_backoffice do
    get 'welcome/index'
    get 'profile', to: 'profile#edit'
    patch 'profile', to: 'profile#update'
    resources :pilot, only: [:index, :edit, :update, :new, :create, :destroy]
    resources :operator, only: [:index, :edit, :update, :new, :create, :destroy]
    resources :vessel, only: [:index, :edit, :update, :new, :create, :destroy]
    resources :terminal, only: [:index, :edit, :update, :new, :create, :destroy]
    resources :next_maneuvers, only: [:index, :edit, :update, :new, :create, :destroy]
    resources :performed_maneuvers, only: [:index, :edit]
  end
  
  devise_for :operators
  devise_for :pilots
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :site do
    get  'welcome/index'
    get  'maneuvers_performed/index'
    get  'next_maneuvers/index'
    #get  'search', to: 'search#questions'
    #get  'subject/:subject_id/:subject', to: 'search#subject' , as: 'search_subject'
    #post 'answer', to: 'answer#question'
  end
   #toda vez que a aplicação for iniciada com seu endereço padrão, será redirecionada para welcome#index
   root to: 'site/welcome#index'
end

app/controllers/pilots_backoffice/dashboard_controller.rb
class PilotsBackoffice::DashboardController < PilotsBackofficeController
    def index
        @pilot = Pilot.find(current_pilot.id)
    end
end

app/controllers/pilots_backoffice/my_next_maneuvers_controller.rb
class PilotsBackoffice::MyNextManeuversController < PilotsBackofficeController
    def index
        pilot = Pilot.find(current_pilot.id)
        pilot_profile_id = pilot.pilot_profile.id
        maneuvers_from_this_pilot = Maneuver.where(pilot_profile_id: pilot_profile_id)
        @maneuvers = maneuvers_from_this_pilot.where(is_finished: false).order('date_maneuver ASC, time_maneuver ASC')
    end

    def edit
        @maneuver = Maneuver.find(params[:id])

        @grades_options = []
        (1..5).each  do |grade|
            @grades_options.push([grade, grade])
        end
        
    end

    def update
        @maneuver = Maneuver.find(params[:id])

        @maneuver.relatory.maneuver_description = params[:maneuver][:relatory][:maneuver_description]
        @maneuver.relatory.vessel_tendecies = params[:maneuver][:relatory][:vessel_tendecies]
        @maneuver.relatory.maneuver_safety = params[:maneuver][:relatory][:maneuver_safety].to_i
        @maneuver.relatory.ladder_safety = params[:maneuver][:relatory][:ladder_safety].to_i
        @maneuver.is_finished = true

        pilot_statistic = PilotStatistic.find_or_create_by(pilot: current_pilot)
        pilot_statistic.total_maneuvers+=1
        pilot_statistic.avg_maneuver_safety = (((pilot_statistic.total_maneuvers-1)*pilot_statistic.avg_maneuver_safety) + @maneuver.relatory.maneuver_safety)/ pilot_statistic.total_maneuvers
        pilot_statistic.avg_ladder_safety = (((pilot_statistic.total_maneuvers-1)*pilot_statistic.avg_ladder_safety) + @maneuver.relatory.ladder_safety)/ pilot_statistic.total_maneuvers
        if  @maneuver.save! && @maneuver.relatory.save! && pilot_statistic.save!
            #bypass_sign_in(@pilot)
            #Update Statistics
           

            redirect_to pilots_backoffice_my_next_maneuvers_path, notice: "Relatório Enviado com Sucesso!"
        else
            render :edit
        end
    end
    
end

app/controllers/pilots_backoffice/my_performed_maneuvers_controller.rb
class PilotsBackoffice::MyPerformedManeuversController < PilotsBackofficeController
    def index
        pilot = Pilot.find(current_pilot.id)
        pilot_profile_id = pilot.pilot_profile.id
        maneuvers_from_this_pilot = Maneuver.where(pilot_profile_id: pilot_profile_id)
        @maneuvers = maneuvers_from_this_pilot.where(is_finished: true).order('date_maneuver ASC, time_maneuver ASC')
    end

    def edit
        @maneuver = Maneuver.find(params[:id])
    end

end

app/controllers/pilots_backoffice/profile_controller.rb
class PilotsBackoffice::ProfileController < PilotsBackofficeController
    before_action :set_user
    
    def edit
        @pilot.build_pilot_profile if @pilot.pilot_profile.blank?
    end

    def update
        if @pilot.update(params_pilot)
            bypass_sign_in(@pilot)
            redirect_to pilots_backoffice_profile_path, notice: "Perfil do Prático atualizado com sucesso!"
        else
           render :edit
        end
    end

    private

    def set_user
        @pilot = Pilot.find(current_pilot.id)
    end

    def params_pilot
        params.require(:pilot).permit(:email, :password, :password_confirmation,
        pilot_profile_attributes: [:id, :first_name, :last_name, :address, :birthdate])
    end
end

app/controllers/pilots_backoffice/welcome_controller.rb
class PilotsBackoffice::WelcomeController < PilotsBackofficeController
  def index
  end
end

app/controllers/pilots_backoffice_controller.rb
class PilotsBackofficeController < ApplicationController
    layout 'pilots_backoffice'
end

app/helpers/pilots_backoffice/dashboard_helper.rb
module PilotsBackoffice::DashboardHelper
end

app/helpers/pilots_backoffice/my_next_maneuvers_helper.rb
module PilotsBackoffice::MyNextManeuversHelper
end

app/helpers/pilots_backoffice/my_performed_maneuvers_helper.rb
module PilotsBackoffice::MyPerformedManeuversHelper
end

app/helpers/pilots_backoffice/profile_helper.rb
module PilotsBackoffice::ProfileHelper
end

app/helpers/pilots_backoffice/welcome_helper.rb
module PilotsBackoffice::WelcomeHelper
end

app/helpers/pilots_backoffice_helper.rb
module PilotsBackofficeHelper
end

app/views/pilots_backoffice/my_performed_maneuvers/edit.html.erb
<div class="row">
    <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
            <div class="x_title">
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <% if @maneuver.errors.any?%>
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <h5 class="alert-heading">Erros Encontrados</h5>
                        <ul>
                            <% @maneuver.errors.full_messages.each  do |message| %>
                            <li style="color:black; font-size:15px"> <%= message %></li>
                            <%end%>
                        </ul>
                        <button class="close" type="button" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                <% end %>

                <%= form_with(url:'#', model: @maneuver, local: true) do |form| %>
                    <%= form.fields_for :relatory do |relatory_form| %>
                       <div class="item form-group">
                        <div class="row" >
                            <%=relatory_form.label 'Descrição da Manobra', class:"col-md-4 mb-1", style:"color:black; font-size:20px"%>
                        </div>
                        
                        <div class="row">
                          <div class="col-md-8 mb-3 ">
                            <%=relatory_form.text_area :maneuver_description, value: @maneuver.relatory.maneuver_description, class:"form-control", rows: 10, :required => 'required', readonly: true%>
                          </div>
                        </div>

                    <div class="item form-group">
                        <div class="row">
                            <%=relatory_form.label 'Tendências do Navio', class:"col-md-4 mb-1",style:"color:black; font-size:20px"%>
                        </div>
                        <div class="row">
                          <div class="col-md-8 mb-3">
                            <%=relatory_form.text_area :vessel_tendecies, value:  @maneuver.relatory.vessel_tendecies, class:"form-control", rows: 10, :required => 'required', readonly: true %>
                          </div>
                        </div>
                            
                        <div class="item form-group">
                            <div class="row">
                                    <div class="col-md-8 mb-3">
                                        <%=relatory_form.label 'Nota para segurança da manobra', class:"col-md-6 mb-1", style:"color:black; font-size:20px"%>
                                        <%=relatory_form.text_field :maneuver_safety, value:  @maneuver.relatory.maneuver_safety, class:"form-control", :required => 'required', readonly: true %>
                                </div>
                            </div>
                        </div>

                         <div class="item form-group">
                            <div class="row">
                                    <div class="col-md-8 mb-3">
                                        <%=relatory_form.label 'Nota para segurança da escada', class:"col-md-6 mb-1", style:"color:black; font-size:20px"%>
                                        <%=relatory_form.text_field :ladder_safety, value:  @maneuver.relatory.ladder_safety, class:"form-control", :required => 'required', readonly: true %>
                                </div>
                            </div>
                        </div>
                    <%end%>

        
                    </div>
                    

                <% end %>

                <div class="ln_solid"></div>
                    <div class="item form-group">
                        <div class="col-md-6 col-sm-6 offset-md-3">
                        <%= link_to "Voltar", pilots_backoffice_my_performed_maneuvers_path, class:"btn btn-primary"%>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

app/views/pilots_backoffice/my_performed_maneuvers/index.html.erb
<h1> My performed Manuvers </h1>